config/routes.rb
Rails.application.routes.draw do
  resources :writeups
  root to: 'writeups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/writeup.rb
class Writeup < ApplicationRecord
    def chancge
        create_table :writeups do |t|
            t.string :tournament_name, null: false
            t.datetime :startdate
            t.string :problem_name
            t.string :problem_type, null: false
            t.string :description, null: false
            
            t.timestamps
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/writeups_controller.rb
class WriteupsController < ApplicationController
  def index
    @writeups = Writeup.all
  end

  def new
    @writeup = Writeup.new
  end

  def create
    writeup = Writeup.new(writeup_params)
    writeup.save!
    redirect_to writeups_path, notice: "登録完了"
  end

  def show
    @writeup = Writeup.find(params[:id])
  end

  def edit
    @writeup = Writeup.find(params[:id])
  end

  def update
    writeup = Writeup.find(params[:id])
    writeup.update!(writeup_params)
    redirect_to writeups_url, notice: "writeup「#{writeup.tournament_name}を更新しました」"
  end

  def destroy
    writeup = Writeup.find(params[:id])
    writeup.destroy
    redirect_to writeups_url, notice: "記事「#{writeup.tournament_name}を削除しました」"
  end

  private

  def writeup_params
    params.require(:writeup).permit(:tournament_name, :startdate, :problem_name, :problem_type, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/writeups_helper.rb
module WriteupsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MyWriteUp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.nabvar-expand-md.navbar-light.bg-light
      .navbar-brand MyWriteUp
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    = yield

app/views/writeups/_form.html.slim
= form_with model: writeup, local: true do |f|
    .form-group
        = f.label :tournament_name, '大会名'
        = f.text_field :tournament_name, class: 'form-control'

    .form-group
        = f.label :startdate, '開始日時'
        = f.date_select :startdate, class: 'form-control'

    .form-group
        = f.label :problem_name, '問題名'
        = f.text_field :problem_name, class: 'form-control'

    .form-group
        = f.label :problem_type, '問題種類'
        = f.select :problem_type, [["Crypto", "Crypto"], ["Bin,Rev", "Bin,Rev"], ["Forensics", "Forensics"], ["Web", "Web"], ["Pwn", "Pwn"], ["Osint", "Osint"], ["Misc", "Misc"]], class: 'form-control'

    .form-group
        = f.label :description, '解説'
        = f.text_area :description, class: 'form-control'
   
    = f.submit nil, class: 'btn btn-primary'

app/views/writeups/edit.html.slim
h1 Writeup編集


.nav.justify-content-end
    = link_to '一覧' , writeups_path, class: 'nav-link'

= render partial: 'form', locals: { writeup: @writeup }

app/views/writeups/index.html.slim
h1 タスク一覧

= link_to '新規登録', new_writeup_path, class: 'btn btn-primary'


.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th= Writeup.human_attribute_name(:tournament_name)
            th= Writeup.human_attribute_name(:startdate)
            th= Writeup.human_attribute_name(:problem_name)
            th= Writeup.human_attribute_name(:problem_type)
            th
        
    tbody
        - @writeups.each do |writeup|
            tr
                /td= writeup.tournament_name
                td= link_to writeup.tournament_name, writeup
                /td= writeup.startdate
                td= link_to writeup.startdate, writeup
                /td= writeup.problem_name
                td= link_to writeup.problem_name
                /td= writeup.problem_type
                td= link_to writeup.problem_type
                td= link_to '編集', edit_writeup_path(writeup), class: 'btn btn-primary mr-3'
                td= link_to '削除', writeup, method: :delete, data: { confirm: "記事「#{writeup.tournament_name}を削除しますか？」" }, class: 'btn btn-danger'

app/views/writeups/new.html.slim
h1 新しいWriteUpを追加

.nav.justify-content-end
    = link_to '一覧' , writeups_path, class: 'nav-link'


= render partial: 'form', locals: { writeup: @writeup }

app/views/writeups/show.html.slim
h1 Writeup詳細


.nav.justify-content-end
    = link_to '一覧' , writeups_path, class: 'nav-link'


table.table.table-hover
    tbody
        tr
            th= Writeup.human_attribute_name(:tournament_name)
            td= @writeup.tournament_name
        tr
            th= Writeup.human_attribute_name(:startdate)
            td= @writeup.startdate

        tr
            th= Writeup.human_attribute_name(:problem_name)
            td= @writeup.problem_name
        tr
            th= Writeup.human_attribute_name(:problem_type)
            td= @writeup.problem_type
        tr
            th= Writeup.human_attribute_name(:description)
            td= @writeup.description